import { Application } from 'egg';
module.exports = (app: Application) => {
  const { STRING } = app.Sequelize;

  // const sample = [
  //   '2018-12-03',
  //   '000000026168042',
  //   '王**',
  //   '01',
  //   '******19770417****',
  //   '33051',
  //   '52.3',
  //   '0.0',
  //   '0.0',
  //   '52.3',
  //   '0.0',
  //   '0.0',
  //   '0.0',
  //   '0.0',
  //   '52.3',
  //   '50',
  //   '48.36',
  //   '0.0',
  //   '0.0',
  //   '0.0',
  //   '0.0',
  //   '137********',
  // ];

  // const sample2 = {
  //   'data_date': '2018-12-03',
  //   'cust_core_no': '000000026168042',
  //   'cust_name': '王**',
  //   'cert_type': '01',
  //   'cert_no': '******19770417****',
  //   'branch_code': '33051',
  //   '90d_balance_RMB': '52.3',
  //   '90d_fund_RMB': '0.0',
  //   '90d_sg_RMB': '0.0',
  //   '90d_saving_RMB': '52.3',
  //   '90d_Tbond_RMB': '0.0',
  //   '90d_bbfin_RMB': '0.0',
  //   '90d_fbbfin_RMB': '0.0',
  //   '90d_sx_RMB': '0.0',
  //   '90d_assets_RMB': '52.3',
  //   'assets_rating': '50',
  //   'balance_RMB': '48.36',
  //   'gbcard_90d': '0.0',
  //   'gbcard_type': '0.0',
  //   'gbcard_level': '0.0',
  //   'mscard_90d': '0.0',
  //   'mscard_type': '137********',
  // };

  return app.model.define('g_customer_cust_assets_rating', {
    'data_date': STRING,
    'cust_core_no': STRING,
    'cust_name': STRING,
    'cert_type': STRING,
    'cert_no': STRING,
    'branch_code': STRING,
    '90d_balance_RMB': STRING,
    '90d_fund_RMB': STRING,
    '90d_sg_RMB': STRING,
    '90d_saving_RMB': STRING,
    '90d_Tbond_RMB': STRING,
    '90d_bbfin_RMB': STRING,
    '90d_fbbfin_RMB': STRING,
    '90d_sx_RMB': STRING,
    '90d_assets_RMB': STRING,
    'assets_rating': STRING,
    'balance_RMB': STRING,
    'gbcard_90d': STRING,
    'gbcard_type': STRING,
    'gbcard_level': STRING,
    'mscard_90d': STRING,
    'mscard_type': STRING,
    'mscard_level': STRING,
    'yjxcard_90d': STRING,
    'yjxcard_type': STRING,
    'yjxcard_level': STRING,
    'srcard_90d': STRING,
    'srcard_type': STRING,
    'srcard_level': STRING,
    'max_card_level': STRING,
    'addr': STRING,
    'tele_phone': STRING,
    'mobile_phone': STRING,
  });
};
